version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'

  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: 'P@ssw0rd!'
      ACCEPT_EULA: 'Y'
      MSSQL_USER: 'SA'
      MSSQL_PID: 'Developer'
    volumes:
      - 'mssql_data:/var/opt/mssql'

volumes:
  mssql_data: